version: '3.8'

services:
  bot:
    build: .
    container_name: curiosity-bot
    # Load your existing .env for DISCORD_TOKEN, SERVER_API_KEY, etc.
    env_file:
      - .env
    # Override so model_req will POST to your host’s LLM on port 11434
    environment:
      URL_GENERATE: http://host.docker.internal:11434/api/generate
      API_KEY:      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmZTRmYjA4LTQ1NzItNGI0NC1iNTNmLTk5NDNkZWYwY2NmMyJ9.5E7j9QfsHolpENgDMyQH0QrtgBj2ZhA5jtI7Gl1r2hM
    volumes:
      - .:/app:ro
    restart: unless-stopped
